version: '2'
services:
    jhipsternewcompany-app:
        image: jhipsternewcompany
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsternewcompany-mysql:3306/jhipsternewcompany?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipsternewcompany-elasticsearch:9300
        ports:
            - 8080:8080
    jhipsternewcompany-mysql:
        extends:
            file: mysql.yml
            service: jhipsternewcompany-mysql
    jhipsternewcompany-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsternewcompany-elasticsearch
